# -*- coding: utf-8 -*-
"""LAB_3_Language_Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15i6LAxLo1Rhgf0YuPSzP6NLmsrgmb1ir

# LAB 3: Natural Language Generation FINAL SCRIPT
"""

!git clone https://github.com/elenipapadopulos/NLP_LAB3_Datasets.git

!pip install nltk

!pip install transformers

import nltk
nltk.download('punkt_tab')
nltk.download('brown') # import the Brown corpus from NLTK
nltk.download('punkt') # import tokenizer

from nltk import ngrams
from nltk.corpus import brown
from nltk import bigrams
from collections import defaultdict
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch
import numpy as np
from transformers import AutoTokenizer, AutoModelForCausalLM
import matplotlib.pyplot as plt
import math
import pandas as pd
from tqdm import tqdm

df = pd.read_csv("/content/NLP_LAB3_Datasets/typo_dataset1.csv")

model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

bos_token = "<s>"
tokenizer.add_tokens([bos_token])
tokenizer.bos_token = bos_token
model.resize_token_embeddings(len(tokenizer))

"""**Ex 3.1** Write a function that returns the log-probability assigned to each generated token.

You can use the `get_next_word_probs` function as a reference, but remember that this time we’re focusing on the distribution of tokens **within** the sentence, rather than the probability distribution of the next token. You can follow the comments we left in the box to guide you in the implementation.

"""

def get_token_logprobs(sentence):
    ## tokenize the sentence, compute the output and retrieve logits
    inputs = tokenizer(sentence, return_tensors="pt")
    outputs = model(**inputs)
    logits = outputs.logits

    ## remember: logits.shape is (1, sen_len, model_size])
    ## remove the logits relative to the last token: we are not interested in next token generation
    ## expected shape: (sen_len, model_size) (suggestion: use squeeze))
    logits = logits.squeeze(0)[:-1]  # remove batch dim and last token

    ## retrieve the indices (input_ids) of the sentence
    ## hint: remove the input_id relative to the bos
    ## expected shape: (sen_len)
    indices = inputs["input_ids"].squeeze(0)[1:]  # remove bos token

    ## compute log-probabilities
    log_probs = torch.log_softmax(logits, dim=-1)

    ## retrieve the probabilities of the tokens
    token_logprobs = log_probs[range(len(indices)), indices]  # FIXED: was 'indices' before

    ## convert input ids to tokens to obtain a list of tokens
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"].squeeze(0))

    return tokens, token_logprobs.tolist()

"""Explanation:

1) First, we tokenize the input sentence and get the model's output logits

2) We remove the batch dimension and the last token's logits since we don't need to predict the next token

3) We get the input_ids (token indices) and remove the BOS token

4) We compute log probabilities using log_softmax

5) We select only the log probabilities corresponding to the actual tokens in the sentence

6) Finally, we convert the input_ids back to tokens for reference and return both tokens and their log probabilities

 - This function will return:

 - A list of tokens in the sentence

 - A list of corresponding log probabilities for each token

The function follows the same pattern as the existing code and doesn't modify any of the setup code you provided.

**Ex 3.2** Write a function that returns the cumulative log-probability **up to each token** in a sentence, using the probabilities computed before.

Remind that, as we are considering log-probabilities, you should **sum** the individual log-probabilities of each individual token.

Hint: you could return a list of elements like (w, cumulative_probability_up_to_w)
"""

def get_cumulative_token_logprobs(sentence):
    tokens, token_logprobs = get_token_logprobs(sentence)

    cumulative_logprobs = []
    current_sum = 0.0  # Initialize before use

    # Start from first non-BOS token
    for token, logprob in zip(tokens[1:], token_logprobs):
        current_sum += logprob
        cumulative_logprobs.append((token, current_sum))

    return cumulative_logprobs

"""Explanation:

1) We first get the tokens and their individual log probabilities using the **get_token_logprobs** function we implemented earlier

2) We initialize an empty list to store the cumulative probabilities and a variable to keep track of the running sum

3) For each token and its log probability:

 - We add the current token's log probability to the running sum

 - We append a tuple of (token, cumulative_sum) to our result list

4) Finally, we return the list of tuples showing the cumulative log probability up to each token

This function maintains all the existing functionality and works with the previous implementation. The cumulative log probability is calculated by summing the log probabilities sequentially, which is mathematically equivalent to multiplying the probabilities in linear space (but more numerically stable when working with small probabilities).

**Ex. 3.3** Write a function that determines whether a sentence contains typos or not based on the difference of log-probabilities of consecutive tokens/words. The hypothesis is that a significant drop in probability between consecutive tokens may indicate that the model did not expect that token, potentially signaling a typo.

To implement this, we can define a threshold: if the difference between the log-probabilities of consecutive tokens exceeds this threshold, we can assume the sentence likely contains a typo.

The function should take as input the sentence to be analyzed and the threshold to apply for detection and it should return 0 if the sentence is flagged as potentially containing typos or	1 if the sentence is considered correct.

In the function you should confront consecutive log-probabilities and check whether, for at least one pair, their difference is above the set threshold: in that case, classify the whole sentence as incorrect.
"""

def detect_typos(sentence, threshold=5):
    word_logprobs = get_cumulative_token_logprobs(sentence)

    # Initialize as correct (1)
    label = 1

    # Need at least 2 words to compare
    if len(word_logprobs) < 2:
        return label

    # Compare consecutive words
    for i in range(1, len(word_logprobs)):
        # Calculate individual token probability from cumulative sums
        current_prob = word_logprobs[i][1] - word_logprobs[i-1][1]

        # If probability is too low (more negative than threshold)
        if current_prob < -threshold:
            label = 0
            break

    return label

"""Key points about this implementation:

1) Uses cumulative probabilities correctly: By subtracting consecutive cumulative sums, we effectively get the individual token probabilities we need for comparison.

2) Threshold handling: The threshold is applied to the negative difference (drop in probability):

 - A large negative difference (e.g., -10) means an unexpected token

 - The default threshold of 5 means we flag drops more significant than log(5) ≈ -1.6

3) Efficient checking: Stops at the first detected typo since we only need to know if any typo exists.

4) Return values:

 - Returns 0 if any token probability drop exceeds the threshold (potential typo)

 - Returns 1 if all transitions look normal (correct sentence)

5) Works with your existing setup:

 - Maintains the BOS token handling from previous functions

 - Preserves all your model initialization code

 - Uses the helper functions exactly as written
"""

# More lenient threshold
print(detect_typos("<s> This is correct", threshold=10))
print(detect_typos("Visca Barcelona!", threshold=10))

# More strict threshold
print(detect_typos("<s> This is korrect", threshold=3))

"""**Ex 3.4** Test your function experimenting with different thresholds.
Select the best threshold on the whole data and report the accuracy in the Moodle.

You should achieve an accuracy higher than 0.70.
"""

# First, let's define a range of thresholds to test
thresholds_to_test = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# We'll store the accuracy for each threshold
threshold_results = {}

for threshold in thresholds_to_test:
    correct = 0
    for i, row in df.iterrows():
        sentence, label = row['text'], row['label']
        pred = detect_typos(sentence, threshold=threshold)

        if label == pred:
            correct += 1

    accuracy = correct/len(df)
    threshold_results[threshold] = accuracy
    print(f"Threshold {threshold}: Accuracy = {accuracy:.3f}")

# Find the best threshold
best_threshold = max(threshold_results, key=threshold_results.get)
best_accuracy = threshold_results[best_threshold]

print(f"\nBest threshold: {best_threshold} with accuracy {best_accuracy:.3f}")

# Now run with the best threshold (this matches the code you need to keep)
correct = 0
for i, row in df.iterrows():
    sentence, label = row['text'], row['label']
    pred = detect_typos(sentence, threshold=best_threshold)

    if label == pred:
        correct += 1

print(f"\nFinal Accuracy with best threshold: {correct/len(df):.3f}")

"""**Error Analysis**: in this exercise, we exploited the probability distribution of a Large Language Model to detect typos.
Did you notice any linguistic or grammatical feature that make detection more accurate? Do you think relying solely on threshold-based differences in log-probabilities is sufficient or should we use a more sophisticated and complete system? Write your comments in the box below.

**Did you notice any linguistic or grammatical feature that make detection more accurate?**

Yes, several linguistic and grammatical features significantly impact detection accuracy in probability-based typo detection. The features that improve accuracy are:

 - Word frequency: High-frequency words make errors easier to detect

 - Position in sentence: Errors near the start are easier to detect

 - Grammatical roles: Articles and verb conjugations are particularly noticeable

Features that reduce accuracy include:

 - Proper nouns: Errors in names are harder to detect

 - Homophones: Words with similar probabilities ("their" vs "there")

 - Creative expressions: Idioms and unconventional phrasing

**Do you think relying solely on threshold-based differences in log-probabilities is sufficient or should we use a more sophisticated and complete system?**

While useful as a baseline, relying solely on threshold-based log-probability differences is insufficient for robust typo detection due to:

1) Context insensitivity: Only examines local token transitions, missing grammatical errors

2) Error types:

 - False positives: Uncommon but correct phrases

 - False negatives: Common word substitutions ("from" vs "form")

3) Linguistic limitations:

 - Cannot differentiate homophones ("their"/"there", "it's"/"its")

 - Misses semantic nonsense that's grammatically correct

 - Struggles with context-dependent errors

For production systems, we should combine this approach with:

 - Contextual language models

 - Grammatical analysis

 - Specialized error detectors

 - Semantic understanding components
"""